### PR TITLE
Fixed bug in deduplicate mesh & added test. 

### PR DESCRIPTION
**Pull request by gattia**

### CODE REVIEW

**Comment by gattia** [comment]
As I made the pull request I noticed the tests arent being run. You can add the tests being run to GH actions which is a nice feature to make sure everything is running as expected. 

You can also integrate it to automatically push new builds to pypi. 

I created a template library a while ago that outlines a few of these things incase its helpful: https://github.com/gattia/template_python_library

**Comment by fwilliams** [comment]
Looks great! I'll merge after the CI passes.

With regards to testing, good catch! I'm super busy lately. Is there any chance you could send another PR that makes the CI run tests? I'd hugely appreciate this!

**Comment by gattia** [comment]
I hadnt actually noticed got GHA before 🤦‍♂️. I dont think its something I'll be able to get to... I've been putting off adding GHA for tests and pypi for a package of mine for 6 months 🙃

**Comment by fwilliams** [comment]
No worries! Thanks a lot for the pull request!

**Pull request merged**
